server:
  port: 9000
  
spring:
  application:
    name: microservice-zuul
 
zuul:
  prefix: /atguigu
  ignored-services: microsercice-dept
  routes:
    mydept.serviceId: microsercice-dept 
    mydept.service: mydept/**
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
    